name: anatolian_coins
description: Anatolian Coins (NumisTR-backed) mobile app with OIDC login (PKCE).
publish_to: "none"
version: 0.4.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  go_router: ^14.2.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  flutter_appauth: ^6.0.2
  url_launcher: ^6.3.1
  
  # Yeni eklenenler
  share_plus: ^10.0.2              # Paylaşma
  path_provider: ^2.1.4            # Dosya yolu
  flutter_cache_manager: ^3.4.1   # Gelişmiş cache
  sqflite: ^2.3.3                  # Çevrimdışı veritabanı
  path: ^1.9.0                     # Dosya yolu yardımcıları
  permission_handler: ^11.3.1     # İzinler (çevrimdışı için)

  # Camera & Recognition
  camera: ^0.10.5+9                # Kamera erişimi
  image_picker: ^1.0.7             # Galeri seçimi
  image: ^4.1.7                    # Image manipulation
  flutter_image_compress: ^2.2.0   # Sıkıştırma
  crop_your_image: ^1.0.2          # Crop/rotate

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true