name: anatolian_coins
description: Anatolian Coins (NumisTR-backed) mobile app with OIDC login (PKCE).
publish_to: "none"
version: 0.3.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  dio: ^5.7.0
  go_router: ^14.2.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2
  flutter_appauth: ^6.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
