class RegionData {
  static const Map<String, String> regionNames = {
    'pisidia-coins': 'Pisidia',
    'lydia-coins': 'Lidya',
    'ionia-coins': 'İonia',
    'caria-coins': 'Karya',
    'lycia-coins': 'Likya',
    'phrygia-coins': 'Frigya',
    'mysia-coins': 'Misia',
    'bithynia-coins': 'Bitinya',
    'pamphylia-coins': 'Pamfilya',
    'cilicia-coins': 'Kilikya',
    'cappadocia-coins': 'Kapadokya',
    'galatia-coins': 'Galatya',
    'aeolis-coins': 'Ailios',
    'troas-coins': 'Troya',
    'paphlagonia-coins': 'Paflagonya',
    'pontus-coins': 'Pontus',
    'other-ancient-regions-coins': 'Diğer',
  };

  /// Popularity order for regions (based on coin count and user interest)
  /// Higher number = more popular, shows first
  static const Map<String, int> regionPopularity = {
    'lydia-coins': 100,       // En popüler - Croeseid, Sardis
    'ionia-coins': 95,        // Ephesus, Miletus, Smyrna
    'caria-coins': 90,        // Halicarnassus, Knidos, Rhodes
    'lycia-coins': 85,        // Patara, Xanthos
    'phrygia-coins': 80,      // Laodiceia, Hierapolis
    'cilicia-coins': 75,      // Tarsus, Side
    'pamphylia-coins': 70,    // Aspendos, Perge, Side
    'mysia-coins': 65,        // Pergamum, Cyzicus
    'pisidia-coins': 60,      // Selge, Sagalassus
    'bithynia-coins': 55,     // Nicomedia, Nicaea
    'cappadocia-coins': 50,   // Caesarea
    'galatia-coins': 45,      // Ancyra
    'troas-coins': 40,        // Troy
    'aeolis-coins': 35,       // Ailios
    'pontus-coins': 30,       // Pontus
    'paphlagonia-coins': 25,  // Paflagonya
    'other-ancient-regions-coins': 0, // Her zaman en altta
  };

  /// Veritabanındaki gerçek darphane isimleri (nomisma.org formatında)
  static const Map<String, List<String>> mints = {
    'aeolis-coins': [
      'aegae_aeolis',
      'aeolis',
      'apollonia_aeolis',
      'attaea',
      'cilla',
      'cyme_aeolis',
      'elaea',
      'gargara_aeolis',
      'gryneium',
      'heraclea_aeolis',
      'killa',
      'larissa_aeolis',
      'magnesia_ad_sipylum',
      'myrina_aeolis',
      'neonteichos',
      'notium',
      'pitane',
      'temnos',
      'temnus',
      'tisna',
    ],
    'bithynia-coins': [
      'apamea_bithynia',
      'bithynia',
      'bithynium-claudiopolis',
      'caesarea_germanica',
      'calchedon',
      'ce',
      'cianus',
      'cius',
      'creusa',
      'dia_bithynia',
      'hadriani',
      'heraclea_pontica',
      'juliopolis',
      'metropolis_bithynia',
      'nicaea',
      'nicomedia',
      'prusa_ad_olympum',
      'prusias_ad_hypium',
      'tium',
    ],
    'cappadocia-coins': [
      'ariarathia',
      'caesarea_cappadocia',
      'cappadocia',
      'comana_cappadocia',
      'cybistra',
      'eusebeia',
      'mazaca',
      'nora_cappadocia',
      'tyana',
    ],
    'caria-coins': [
      'alabandus',
      'alinda',
      'amyzon',
      'antiocheia_ad_maeandrum',
      'aphrodisias',
      'apollonia_salbaces',
      'astypalaea',
      'attuda',
      'bargylia',
      'calynda',
      'caria',
      'caunus',
      'ceramus',
      'chalcetor',
      'cidramus',
      'cnidus',
      'cos',
      'cys',
      'erize',
      'euromus',
      'gordiuteichos',
      'halicarnassus',
      'harpasa',
      'hydisus',
      'hyllarima',
      'iasus',
      'idyma',
      'mylasa',
      'myndus',
      'naxos_caria',
      'neopolis_caria',
      'nisyros',
      'orthosia_caria',
      'plarasa',
      'rhodes',
      'sebastopolis_caria',
      'stratoniceia',
      'syangela',
      'syme',
      'tabae',
      'telos',
      'termesos_ou_termessos_by_oinonada',
      'thera',
      'tlos',
      'trapezopolis',
    ],
    'cilicia-coins': [
      'adana',
      'adrasus',
      'aegae_cilicia',
      'alexandria_ad_issum',
      'anamurium',
      'anazarbus',
      'anchiale_cilicia',
      'antiocheia_ad_cragum',
      'antiocheia_ad_pyramum',
      'aphrodisias_cilicia',
      'augusta_cilicia',
      'ba_e',
      'balsa',
      'caesarea_ad_anazarbum',
      'carbaca',
      'celenderis',
      'cestrus',
      'characene',
      'cilicia',
      'claudiopolis_cilicia',
      'colybrassus',
      'coropissus',
      'corycus',
      'diocaesarea_cilicia',
      'eirenopolis',
      'epiphaneia_cilicia',
      'flaviopolis_cilicia',
      'germanicopolis_cilicia',
      'hierapolis_castabala',
      'holmi',
      'iotape',
      'issus',
      'lalassis',
      'lamus',
      'laodicea_ad_mare',
      'mallus',
      'mopsuestia',
      'myriandrus',
      'nagidus',
      'olba',
      'philadelphia_cilicia',
      'rhosus',
      'sebaste_cilicia',
      'seleucia_ad_calycadnum',
      'seleucia_ad_pyramum',
      'soli-pompeiopolis',
      'syedra',
      'tarsus',
      'zephyrion',
    ],
    'galatia-coins': [
      'amadasa',
      'ancyra',
      'eucosmia',
      'galatia',
      'germia',
      'pessinus',
      'tavium',
    ],
    'ionia-coins': [
      'chios',
      'clazomenae',
      'colophon',
      'ephesus',
      'erythrae',
      'gryneium',
      'lebedus',
      'magnesia_ad_maeandrum',
      'metropolis_ionia',
      'miletus',
      'myus',
      'notium',
      'phocaea',
      'phygela',
      'priene',
      'samos',
      'smyrna',
      'teos',
    ],
    'lycia-coins': [
      'aegiali_amorgos',
      'alimus',
      'amorion',
      'andriaca',
      'aperlae',
      'apollonia_lycia',
      'arax',
      'arneae',
      'artymnesus',
      'arualia',
      'arycanda',
      'balbura',
      'bubo',
      'calynda',
      'camanene',
      'candyba',
      'caunus',
      'choma',
      'cibyra',
      'comba',
      'corydala',
      'crya',
      'cyaneae',
      'daedala',
      'gagae',
      'iasus',
      'idyros',
      'isinda_lycia',
      'istlada',
      'linda',
      'lycia',
      'lymira',
      'marmara_lycia',
      'masicytes',
      'myra',
      'nysa_lycia',
      'oenoanda',
      'olympus',
      'patara',
      'phaselis',
      'phellus',
      'pinara',
      'podalia',
      'rhodiapolis',
      'sidyma',
      'telmessus',
      'termesos_ou_termessos_by_oinonada',
      'tlos',
      'trebenda',
      'tyberissos',
      'tyria',
      'xanthos',
    ],
    'lydia-coins': [
      'acrasus',
      'apollonis',
      'apollonoshieron',
      'attaleia_lydia',
      'aureliopolis_lydia',
      'bagis',
      'blandus',
      'briula',
      'caesarea_troketta',
      'caystriani',
      'cilandus',
      'clannuda',
      'daldis',
      'decae',
      'dioshieron',
      'gordus-julia',
      'hermocapelia',
      'hierocaesarea',
      'hypaepa',
      'hyrcanis',
      'lydians',
      'magnesia_ad_sipylum',
      'masdyra',
      'mastaura_lydia',
      'mostene',
      'moxeani',
      'nacrasa',
      'nysa_lydia',
      'philadelphia_lydia',
      'sala_lydia',
      'sardes',
      'satala_lydia',
      'sebaste_lydia',
      'silandus',
      'stratonicopolis-hadrianopolis',
      'tabala',
      'teira_lydia',
      'themisonium_lydia',
      'thryara',
      'thyatira',
      'thyessus',
      'tmolus',
      'tomaris',
      'tralles',
    ],
    'mysia-coins': [
      'abydus',
      'adramyteum',
      'antandrus',
      'apollonia_ad_rhyndacum',
      'assus',
      'atarnus',
      'cyzicus',
      'dardanus',
      'ergasteria',
      'gargara',
      'germen',
      'hadrianeia',
      'hadrianothera',
      'iliolophos',
      'lamponia',
      'lampsacus',
      'miletopolis',
      'mysia',
      'parion',
      'pergamum',
      'perperene',
      'pionia',
      'pitane',
      'placia',
      'poemanenum',
      'priapus',
      'proconnesus',
      'scepsis',
      'sigeum',
      'teuthrania',
      'tiberiopolis_mysia',
      'troas',
      'zeleia',
    ],
    'other-ancient-regions-coins': [
      'arkathiokerta',
      'doliche',
      'iconium',
      'ilistra',
      'isaura',
      'isaura_nova',
      'laodiceia_combusta',
      'laranda',
      'samsosata',
      'savatra',
      'zeugma',
    ],
    'pamphylia-coins': [
      'aspendus',
      'attaleia_pamphylia',
      'etoanna',
      'isyndus',
      'lyrbe',
      'magydus',
      'olbia_pamphylia',
      'pamphylia',
      'perga',
      'pogla',
      'side',
      'silbium',
      'sillyon',
    ],
    'paphlagonia-coins': [
      'abonouteichos',
      'amastris',
      'creteia-flaviopolis',
      'cromna',
      'cytorus',
      'gangra',
      'germaniconpolis_paphlagonia',
      'hadrianopolis_paphlagonia',
      'ionopolis_paphlagonia',
      'neoclaudiopolis',
      'paphlagonia',
      'pompeiopolis_paphlagonia',
      'sesamus',
      'sinope',
      'zaliche',
    ],
    'phrygia-coins': [
      'acciza',
      'acmonia',
      'aezanis',
      'alia',
      'amorion',
      'anabura',
      'ancyna',
      'apameia_phrygia',
      'appia',
      'aristium',
      'blaundus',
      'bria',
      'bruzus',
      'cadi',
      'ceretapa',
      'cibyra',
      'clandus',
      'colossae',
      'cotiaeum',
      'diocleia_phrygia',
      'dionysopolis_phrygia',
      'docimeium',
      'epictetus',
      'erize',
      'eucarpia',
      'eumeneia',
      'fulvia',
      'germanicopolis_phrygia',
      'grimenothyrae',
      'hadrianopolis_phrygia',
      'hierapolis_phrygia',
      'hyrgaleis',
      'ipsus',
      'laodiceia_ad_lycum',
      'lysius',
      'merus',
      'midaeum',
      'midas_city',
      'nacoleia',
      'ocia',
      'oenoanda',
      'otrus',
      'peltae',
      'philomelium',
      'phrygia',
      'phylacaeum',
      'polybotus',
      'prymnesus',
      'sala_phrygia',
      'sanis',
      'sebaste_phrygia',
      'siblia',
      'stectorium',
      'synaus',
      'synnada',
      'themisonium',
      'tiberiopolis',
      'trajanopolis_phrygia',
      'tripolis_phrygia',
    ],
    'pontus-coins': [
      'amaseia',
      'amisus',
      'cabeira',
      'cerasus',
      'comana_pontica',
      'eupatoria',
      'gaziura',
      'magnopolis',
      'neapolis_pontus',
      'nicopolis_pontus',
      'pharnaceia',
      'polemonium',
      'pontus',
      'sebasteia',
      'sebastopolis_pontus',
      'trapezus',
      'zela',
    ],
    'pisidia-coins': [
      'adada',
      'amblada',
      'andeda',
      'antiocheia_pisidia',
      'apollonia_mordiaion',
      'ariassos',
      'baris_pisidia',
      'codrula',
      'colonia_pisidia',
      'comama',
      'conana',
      'cremna',
      'etenna',
      'isinda_pisidia',
      'lagbe',
      'lysinia',
      'olbasa',
      'panemoteichos',
      'pednelissos',
      'pogla',
      'prostanna',
      'sagalassos',
      'sandalion',
      'selge',
      'termessos',
      'timbriada',
      'verbe',
    ],
    'troas-coins': [
      // Migration ile gelenler (Mysia'dan)
      'abydus',
      'antandrus',
      'assus',
      'dardanus',
      'gargara',
      'pionia',
      'scepsis',
      'sigeum',
      'alexandria_troas',
      // Yeni darphaneler (Nomisma)
      'birytis',
      'cebrene',
      'chrysa',
      'gentinus',
      'hamaxitus',
      'ilium',
      'neandreia',
      'ophrynium',
      'polymedium',
      'tenedos',
    ],
  };

  static String getRegionName(String? regionCode) {
    if (regionCode == null || regionCode.isEmpty) return '-';
    return regionNames[regionCode] ?? regionCode;
  }

  static List<String> getMintsForRegion(String? regionCode) {
    if (regionCode == null || regionCode.isEmpty) return [];
    return mints[regionCode] ?? [];
  }

  static List<MapEntry<String, String>> getAllRegions() {
    return regionNames.entries.toList()
      ..sort((a, b) => a.value.compareTo(b.value));
  }

  /// Get regions sorted by popularity (most popular first)
  /// "Diğer Antik Bölgeler" is always last
  static List<MapEntry<String, String>> getRegionsByPopularity() {
    final entries = regionNames.entries.toList();

    // Sort by popularity (descending), "other" always last
    entries.sort((a, b) {
      final popA = regionPopularity[a.key] ?? 0;
      final popB = regionPopularity[b.key] ?? 0;
      return popB.compareTo(popA); // Descending order
    });

    return entries;
  }

  /// Get popularity score for a region
  static int getRegionPopularity(String? regionCode) {
    if (regionCode == null) return 0;
    return regionPopularity[regionCode] ?? 0;
  }
}
